version: "3"

services:
  mongo:
    image: mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    ports:
      - "27017:27017"
  redis:
    image: redis
    ports:
      - "6379:6379"