apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-project
  namespace: default
  labels:
    app: devops-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-project
  template:
    metadata:
      labels:
        app: devops-project
    spec:
      containers:
        - env: 
            - name: discord_sot_token
              valueFrom:
                secretKeyRef:
                  name: devops-project
                  key: discord_sot_token
          name: devops-project
          image: pyrrha/devops-project:latest
