apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-project
  namespace: default
  labels:
    app: devops-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-project
  template:
    metadata:
      labels:
        app: devops-project
    spec:
      containers:
        - name: devops-project
          image: pyrrha/devops-project:latest
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: discord_token
              mountPath: "/bot/discord_token"
              readOnly: true
          volumes:
          - name: discord_token
            secret:
              secretName: discord-sot-token
