apiVersion: v1
kind: Service
metadata:
  name: devops-project
  namespace: default
  labels:
    app: devops-project
spec:
  selector:
    app: devops-project
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      name: http
